[tool.black]
line-length = 79
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | easygp/_version.py
  | versioneer.py 

  # The following are specific to Black, you probably don't want those.
  | blib2to3
  | tests/data
)/
'''
