name: CI pipeline

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.9]

    steps:

    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install requirements 
      run: bash scripts/install_requirements.sh core tests

    - name: Run tests
      run: pytest -v --cov --cov-report xml easybo/_tests

    # - name: Upload code coverage
    #   uses: codecov/codecov-action@v2
    #   timeout-minutes: 10
    #   with:
    #     token: ${{ secrets.CODECOV_TOKEN }}
    #     fail_ci_if_error: false
